### ISSUE TITLE
Rendered style examples don't localize according to style locale

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/Sheldon#20]
@retorquere, I've just noticed that the example reference don't seem to localize according to the `default-locale` locale specified in the style.

E.g. the examples at https://github.com/citation-style-language/styles/pull/4221#issuecomment-514800909 show up in English ("Retrieved from") but the style uses `default-locale="fr-CA"`, and correctly renders in Canadian French in Zotero ("Récupéré de"). I've seen the same discrepancy at https://github.com/citation-style-language/styles/pull/4229#issuecomment-516686037 (the style is British English, with "en-GB", but renders as US English).

**Comment by retorquere** [comment]
See https://github.com/citation-style-language/Sheldon/pull/21

**Comment by rmzelle** [comment]
Thanks for the superquick response!

**Comment by rmzelle** [comment]
(confirmed this works; see e.g. https://github.com/citation-style-language/styles/pull/4232#issuecomment-518046504)
