### ISSUE TITLE
Fine-tuning messages

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/Sheldon#3]
Not sure where to put this, so adding this here. 
One thing that I would like to change is where we include the instructions for editing a pull request. I think it should be in the initial "Great!..." message, not in the "Ooops!" messages. 
a) Less repetitive and 
b) The main reason, we often want people to edit the PRs even when they pass the tests, or they may want to do it themselves. 

Thoughts? Other things to change?

**Comment by rmzelle** [comment]
Just working on this.

**Comment by rmzelle** [comment]
(and those were my thoughts exactly)

**Comment by adam3smith** [comment]
I saw, that's what prompted this. Let's also add Portuguese and French to
the languages spoken. I'm feeling adventurous (and given Zotero experience,
there may be a particular demand.)

On Fri, Dec 4, 2015 at 11:58 AM, Rintze M. Zelle <notifications@github.com>
wrote:

> (and those were my thoughts exactly)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/Sheldon/issues/3#issuecomment-162035608>
> .
>



-- 
Sebastian Karcher, PhD
www.sebastiankarcher.com

**Comment by rmzelle** [comment]
@adam3smith, #2 is ready for review.
