### ISSUE TITLE
Notifications are not working

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/Sheldon#6]
Sheldon no longer posts the build report comments to GitHub. The initial post after creating a PR is still posted.

I recently upgraded to Ruby 2.3.1 in .travis.yml, but the issue arose before that change. Two PRs around the date the issue popped up:

https://github.com/citation-style-language/styles/pull/2171 (good)
https://github.com/citation-style-language/styles/pull/2175 (bad)

Almost certainly related to a recently reported bug in Travis CI: https://github.com/travis-ci/travis-ci/issues/6435

**Comment by rmzelle** [comment]
@inukshuk, there have been some posts from Travis developers on the Travis ticket (see https://github.com/travis-ci/travis-ci/issues/6435#issuecomment-243113182), and Sheldon started working again as well (see e.g. https://github.com/citation-style-language/styles/pull/2188#issuecomment-243230963).

There is some talk about implementing a new authentication method, which goes over my head. It's not clear to me whether Sheldon needs to be updated at some point.

**Comment by inukshuk** [comment]
Yes, we'll have to update to the new auth method soon. (I'll make a note of it)
